### ISSUE TITLE
How are "child packages" being extracted / How much automation could be achievec?

### ISSUE THREAD

**Issue by fmauch** [boschresearch/ROScan#1]
Hi,

first of all, this looks like a very useful project, thank you for attacking this!

In the [clearing concept slides](https://github.com/boschresearch/ROScan/blob/master/ROScan%20clearing%20%20concept.pdf) you note that you download the source of the "main packages" and the "child packages". If one would like to do the same process on packages not included inside your survey: How do you generate the list of all child packages? By recursively (and manually) going through all the `package.xml` files? By using tools like `rospack depends`?

My question aims at: How much of the whole process could be automated in such a way, that users could concentrate on reviewing and manually clearing the package files?

**Comment by JanKirsch** [comment]
Hi fmauch,

thank you for your request and sorry for our late response.  Unfortunately I can not help you.

Our main contributor and knowledge owner @ArneF-oss is right now out of office so he will come directly to you when he is back around the end of september. It can take a little while so please have a couple coffees in between ☕☕☕.

**Comment by ArneF-oss** [comment]
Hi fmauch,
Within the ROScan project we had a predefined list of “main and child” packages. Anyway, for some cross checks I also used the 
`rospack depends` commands.
I think the download of packages and belonging dependencies can be automated with some script. But even if you have downloaded the data, you have to upload them via an API to your review tool.
(For Fossology you might find the needed information at [Fossology-Rest-API](https://www.fossology.org/get-started/basic-rest-api-calls/) )

At least for this project the effort for the manual download/upload of the packages was small compared to the effort of the review.
